
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/proj-rec-f24-06
owner: ucsb-cs156-f24
repo_name: proj-rec-f24-06
pull_requests: [{"author":{"id":"MDQ6VXNlcjQzMzk0Njg0","is_bot":false,"login":"chriswlai","name":"Christopher Lai"},"headRefName":"cl-reqtypes-create","number":81,"title":"CL: Create Page for UCSBOrganization plus tests and stories","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-06/pull/81"},{"author":{"id":"MDQ6VXNlcjQzMzk0Njg0","is_bot":false,"login":"chriswlai","name":"Christopher Lai"},"headRefName":"cl-reqtypes-placeholders","number":77,"title":"CL: Copy Placeholders for RequestType pages; add to App.js/AppNavbar.js","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-06/pull/77"},{"author":{"id":"MDQ6VXNlcjQzMzk0Njg0","is_bot":false,"login":"chriswlai","name":"Christopher Lai"},"headRefName":"cl-reqtypes-table","number":76,"title":"CL: Create RequestTypeTable (team02 style)","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-06/pull/76"},{"author":{"id":"U_kgDOB2_WkA","is_bot":false,"login":"skanda-vasishta","name":""},"headRefName":"sv-recrequest-form","number":75,"title":"added recommendation request form, fixtures, frontend tests (WIP, fix title later)","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-06/pull/75"},{"author":{"id":"MDQ6VXNlcjQzMzk0Njg0","is_bot":false,"login":"chriswlai","name":"Christopher Lai"},"headRefName":"cl-reqtypes-form","number":72,"title":"CL: Create RequestTypeForm (team02 style)","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-06/pull/72"},{"author":{"id":"U_kgDOBs-ReA","is_bot":false,"login":"michaelljiang","name":"Michael Jiang"},"headRefName":"mj-crud","number":71,"title":"MJ - API Endpoints for Recommendation Requests","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-06/pull/71"},{"author":{"id":"MDQ6VXNlcjQzMzk0Njg0","is_bot":false,"login":"chriswlai","name":"Christopher Lai"},"headRefName":"cl-reqtypes-controller","number":69,"title":"CL: Add RequestTypeController for CRUD operations","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-06/pull/69"},{"author":{"id":"MDQ6VXNlcjU1MTYzOTcx","is_bot":false,"login":"ELEXG","name":"Edward Garcia"},"headRefName":"eg-admin-requests","number":68,"title":"eg - placeholder requests page for admin to see all recommendation requests","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-06/pull/68"},{"author":{"id":"U_kgDOB2_WkA","is_bot":false,"login":"skanda-vasishta","name":""},"headRefName":"sv-recommendation-request-b1","number":56,"title":"added entity, repository, and migration for recommendation requests, issue #45, #46","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-06/pull/56"}]
