
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/proj-rec-f24-06
owner: ucsb-cs156-f24
repo_name: proj-rec-f24-06
pull_requests: [{"author":{"id":"MDQ6VXNlcjYzNTg4NzIx","is_bot":false,"login":"SexyCarrots","name":"Xinghan Yang"},"headRefName":"xinghan-dev","number":37,"title":"Delete all files non-related to Request Feature","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-06/pull/37"},{"author":{"id":"U_kgDOBs-ReA","is_bot":false,"login":"michaelljiang","name":"Michael Jiang"},"headRefName":"mj-usertable","number":33,"title":"MJ - Added Professor & Student Columns for User Table and Toggle Buttons","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-06/pull/33"},{"author":{"id":"U_kgDOBs-ReA","is_bot":false,"login":"michaelljiang","name":"Michael Jiang"},"headRefName":"mj-add-old-rec-files","number":32,"title":"adding old recommendation files","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-06/pull/32"}]
