
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/proj-rec-f24-06
owner: ucsb-cs156-f24
repo_name: proj-rec-f24-06
pull_requests: [{"author":{"id":"MDQ6VXNlcjQzMzk0Njg0","is_bot":false,"login":"chriswlai","name":"Christopher Lai"},"headRefName":"cl-reqtypes-create","number":81,"title":"CL: Create Page for RequestTypeCreate plus tests and stories","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-06/pull/81"},{"author":{"id":"U_kgDOB2_WkA","is_bot":false,"login":"skanda-vasishta","name":""},"headRefName":"sv-recrequest-form","number":75,"title":"SV: added recommendation request form, fixtures, frontend tests","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-06/pull/75"}]
