
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/proj-rec-f24-06
owner: ucsb-cs156-f24
repo_name: proj-rec-f24-06
pull_requests: [{"author":{"id":"MDQ6VXNlcjU3NDYyMjQz","is_bot":false,"login":"vprchlik","name":"Victor Prchlik"},"headRefName":"vp-PendingRequestsTableButtons","number":94,"title":"vp - added Accept and Deny buttons and functionality to Pending Requests Table","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-06/pull/94"},{"author":{"id":"MDQ6VXNlcjU3NDYyMjQz","is_bot":false,"login":"vprchlik","name":"Victor Prchlik"},"headRefName":"vp-PendingRequestsTable","number":93,"title":"pc/vp - create new branch from Victor's old branch with only the Pending Request Table","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-06/pull/93"},{"author":{"id":"MDQ6VXNlcjU3NDYyMjQz","is_bot":false,"login":"vprchlik","name":"Victor Prchlik"},"headRefName":"vp-change-pending-req","number":92,"title":"vp - added Accept and Deny functionality for Pending Requests Table","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-06/pull/92"},{"author":{"id":"MDQ6VXNlcjU1MTYzOTcx","is_bot":false,"login":"ELEXG","name":"Edward Garcia"},"headRefName":"eg-professor-pages","number":88,"title":"eg - professor tab on navbar, two placeholders pages for completed requests and statistics","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-06/pull/88"},{"author":{"id":"MDQ6VXNlcjU3NDYyMjQz","is_bot":false,"login":"vprchlik","name":"Victor Prchlik"},"headRefName":"vp-view-pending-req","number":87,"title":"vp - Added basic functionality for frontend Pending Requests","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-06/pull/87"},{"author":{"id":"MDQ6VXNlcjQzMzk0Njg0","is_bot":false,"login":"chriswlai","name":"Christopher Lai"},"headRefName":"cl-reqtypes-create","number":81,"title":"CL: Create Page for RequestTypeCreate plus tests and stories","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-06/pull/81"},{"author":{"id":"U_kgDOB2_WkA","is_bot":false,"login":"skanda-vasishta","name":""},"headRefName":"sv-recrequest-form","number":75,"title":"added recommendation request form, fixtures, frontend tests (WIP, fix title later)","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-06/pull/75"}]
